name: Trigger Installer

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SKYMP5_INSTALLER_REPOSITORY_DISPATCH_PAT }}
          repository: shadowgamingyt/skymp-Balkisteir-LTD_LoneWolf-installer
          event-type: 'on-skymp-push'
          client-payload: |
            {
              "ref": "refs/heads/main",
              "inputs": {}
            }
